name: Hooks-JS Package

on:
    push:
        branches:
            - main

jobs:
    release:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
